---
  language: go
  sudo: false
  notifications:
    email: true
  branches:
  only:
  - master
  - develop
  go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - master
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "mzVO0uc7ZOtxTAifrYen8c30D0KPJ0UbXrl4pO/3qzJ/wIwqdZWUjz3ICNyWsew+TWJMwu3GS7tNj1UuFgrqZaV2Px1K40dl7hG/ZecTFIza2epBBLThksdiALQ/L1n7aJ7orJtFq8sPKkvd3/fcC0tDU0JDVdBTbb91oJ254hWN0vqS6LiFVNE8LHgCgg82MrPMXZsdkIiyuyP7q4k8k4HYQ5s3+jq61TmaLbO7RsM3a7t8ByI5Cd01wA6zrEqiIrkL3S+wc3enhXgi/UldeCHdYTLTE+M0Vsq04oshRXifmD1QUBqrRk8U4aqAHKme62JeT2y7b4+96yRB/lcLE3YTxOHZMh9GXrKFJO38h4Ij0reSWOhAve4F10U7PxFFek+M4/dXjSYtTjkdvIE2RZ+D6djFrvd2PItfuNUu8Ydk4kEtbnM72kXdVI8SBbC3TJfIKYR7Q9nHBZ3jpHws14cX1Myeo8O0W/g69Fhue/pDvaFKnUMX4UzITnaJ11XTP/PveWYN5hg2ak702zyVTiIQJIRXJTTM1XIaY6PeYLY5OIs0yAzZ3aXJTwIL/0KgT0T3FNTRONiDLessbOlMEZe5x/Sg9Rt1XTsE68splFqbdXDGZKph7vmE2PpfTR2EQZsu7ADmYa095FTfz6AqyaEGGWhDR3LhQamMydUfHqk="
    file:
      - cross/ghb0t-linux-amd64.md5
      - cross/ghb0t-windows-386.sha256
      - cross/ghb0t-linux-arm
      - cross/ghb0t-darwin-amd64.md5
      - cross/ghb0t-darwin-amd64
      - cross/ghb0t-solaris-amd64.md5
      - cross/ghb0t-linux-arm64.sha256
      - cross/ghb0t-linux-arm.sha256
      - cross/ghb0t-linux-386.sha256
      - cross/ghb0t-darwin-386.md5
      - cross/ghb0t-windows-386.md5
      - cross/ghb0t-freebsd-amd64.md5
      - cross/ghb0t-linux-arm64.md5
      - cross/ghb0t-linux-arm64
      - cross/ghb0t-freebsd-amd64.sha256
      - cross/ghb0t-freebsd-386.md5
      - cross/ghb0t-linux-amd64.sha256
      - cross/ghb0t-linux-386.md5
      - cross/ghb0t-freebsd-386
      - cross/ghb0t-solaris-amd64.sha256
      - cross/ghb0t-windows-amd64
      - cross/ghb0t-windows-amd64.md5
      - cross/ghb0t-windows-amd64.sha256
      - cross/ghb0t-linux-arm.md5
      - cross/ghb0t-darwin-386.sha256
      - cross/ghb0t-darwin-amd64.sha256
      - cross/ghb0t-windows-386
      - cross/ghb0t-solaris-amd64
      - cross/ghb0t-darwin-386
      - cross/ghb0t-linux-386
      - cross/ghb0t-freebsd-amd64
      - cross/ghb0t-freebsd-386.sha256
      - cross/ghb0t-linux-amd64
    skip_cleanup: true
    on:
      go: tip
      tags: true
    